// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Stop {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Stop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStop(bb:flatbuffers.ByteBuffer, obj?:Stop):Stop {
  return (obj || new Stop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStop(bb:flatbuffers.ByteBuffer, obj?:Stop):Stop {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Stop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startStop(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  Stop.startStop(builder);
  return Stop.endStop(builder);
}
}
